### ISSUE TITLE
PHP 8.x Compatibility

### ISSUE THREAD

**Issue by schwindy** [spatie/laravel-slack-slash-command#104]
### This package is not compatible with PHP v8
https://github.com/spatie/laravel-slack-slash-command/blob/master/composer.json#L19
```
 Problem 1
    - Root composer.json requires spatie/laravel-slack-slash-command ^1.11 -> satisfiable by spatie/laravel-slack-slash-command[1.11.0].
    - spatie/laravel-slack-slash-command 1.11.0 requires php ^7.3 -> your php version (8.0.3) does not satisfy that requirement.
```

I recently created a bot using this package, but when upgrading to PHP v8, I found this package to be incompatible with the new major version of PHP. As PHP 8 is gaining maturity, I think it would be ideal to provide a release that is compatible with it. Laravel itself does support PHP 8. I would highly appreciate this, as otherwise I will need to use another package 😞 🙏

**Comment by freekmurze** [comment]
Feel free to send a PR to make this package compatible with PHP 8.

**Comment by schwindy** [comment]
>Feel free to send a PR to make this package compatible with PHP 8.

@freekmurze Here is a PR doing that: https://github.com/spatie/laravel-slack-slash-command/pull/105
