### ISSUE TITLE
Add source validation 

### ISSUE THREAD

**Issue by renedekat** [spatie/laravel-slack-slash-command#3]
Hi,

First of all, great package!

Secondly, I think that when dealing with live systems, security is paramount, so I was thinking that, if possible, can IP-range checks be added to 

```
    protected function guardAgainstInvalidRequest()
    {
        if (!request()->has('token')) {
            throw InvalidRequest::tokenNotFound();
        }
        if ($this->request->get('token') != $this->config->get('token')) {
            throw InvalidRequest::invalidToken($this->request->get('token'));
        }
    }
```

I haven't checked if Slack commands always originate from a specific IP-range, but if they do, it would add an extra layer of security. Then again, from what I understand Slack runs as AWS Lambda services, so that would make this quite hard to do.

**Comment by freekmurze** [comment]
Hi,

thanks, glad you like it!

of course security is paramount if you're going to couple our package with live systems. However I do not think an IP check is necessary by default for this pacakage. If Slack were to change their IP addresses your slash command would break.

Slack recommends the use of a long enough token, together with a https-connection. If you want extra security you could also check the id of user in the given request.

You're of course free to add an IP check in your own app.

**Comment by renedekat** [comment]
Cheers!
