### ISSUE TITLE
Sharing commands

### ISSUE THREAD

**Issue by barryvdh** [spatie/laravel-slack-slash-command#31]
Do you have any thoughts about sharing commands? Eg. publishing commands to this repo (or other), and perhaps guidelines?

Eg. use SignatureHandler with wildcard as command.

**Comment by freekmurze** [comment]
In general I don't want to be responsible for maintaining code I don't use myself. So sharing commands in this repo isn't a good idea in my mind.

I could add a little section to docs with contributed example commands. An alternative would be that you create a repo yourself with commands you want to sure. I certainly would put a link in the readme / documentation of this package to your repo.

**Comment by barryvdh** [comment]
Ok cool
