### ISSUE TITLE
Unable to post to app

### ISSUE THREAD

**Issue by richdynamix** [spatie/laravel-slack-slash-command#4]
After installing the package I had to manually copy the config as the vendor:publish command did not work - 

```
php artisan vendor:publish --provider="Spatie\SlashCommand\SlashCommandServiceProvider" --tag="config"
Nothing to publish for tag [config].
```

I left the config url to `slack` but when I POST to my domain.app/slack I get route the default `NotFoundHttpException in RouteCollection.php line 161:`.

Should I be defining any routes for this or does the config itself handle the routing? 

I have setup ngrok to use my local homestead app in slack but since this does not work I tried with postman to post directly. Still the same result.

**Comment by freekmurze** [comment]
Did you install the service provider?

**Comment by richdynamix** [comment]
Yeah inside `config/app.php` I added `Spatie\SlashCommand\SlashCommandServiceProvider::class,` as per the docs

**Comment by freekmurze** [comment]
Could you add a dd statement somewhere `SlashCommandServiceProvider` to ensure that it is being called? Everything you described points to the service provider not being registered.

**Comment by richdynamix** [comment]
Added `dd('called inside');` on line 14 of `vendor/spatie/laravel-slack-slash-command/src/SlashCommandServiceProvider.php`

Results were - 

`"called inside"`

It seems to get into the boot method but doesn't seem to apply to the router.

**Comment by freekmurze** [comment]
Does calling `config('laravel-slack-slash-command')` return an array with valid configuration data?

**Comment by richdynamix** [comment]
```
array:3 [
  "url" => "slack"
  "token" => "asdasdasdasdasdasdasd"
  "handlers" => array:2 [
    0 => "MyApp\SlashCommandHandlers\Hodor"
    1 => "Spatie\SlashCommand\Handlers\CatchAll"
  ]
]
```

**Comment by freekmurze** [comment]
what is the output of `route:list`, do you see the slack route there?

**Comment by richdynamix** [comment]
Sorry for the delay. I got it working. On initial check of `route:list` the route was missing so I did a `route:clear` which resolved the issue. Must have been down to the cache 👍🏻

Thanks for your help

**Comment by freekmurze** [comment]
Np, have fun using the package.
