### ISSUE TITLE
Error after installation: syntax error, unexpected ':', expecting ';' or '{'

### ISSUE THREAD

**Issue by jryd** [spatie/laravel-slack-slash-command#41]
I've just been following your blog post (https://murze.be/2016/07/building-a-slack-bot-with-laravel/) and for fun and to test it - used your Hodor class example.

I followed all your installation steps and everything installed fine - however when Slack posts to my Laravel app I get an error that:

> syntax error, unexpected ':', expecting ';' or '{'

Which is referring to `../vendor/spatie/laravel-slack-slash-command/src/Controller.php:31`:

```
public function getResponse(): IlluminateResponse
{
    $this->guardAgainstInvalidRequest();

    $handler = $this->determineHandler();

    try {
        if ($handler instanceof SignatureHandler) {
            $handler->validate();
        }
        $response = $handler->handle($this->request);
    } catch (SlackSlashCommandException $exception) {
        $response = $exception->getResponse($this->request);
    } catch (Exception $exception) {
        $response = $this->convertToResponse($exception);
    }

     return $response->getIlluminateResponse();
}
```

Am I missing something?

**Comment by jryd** [comment]
The catch all class is returning the same error if I comment out the `Hodor` handler.

**Comment by freekmurze** [comment]
The example and package are using  PHP 7 features.  Are you using PHP 7?

**Comment by jryd** [comment]
Sigh...

I was using an online Cloud IDE at the time, it came with PHP 5.6 and I was using PHPBrew to update it to PHP 7 - however this was only doing updating to PHP 7 for the CLI.

After reinstalling it and updating it globally (including Apache) it works a treat.

Looking forward to getting started with this now!
