### ISSUE TITLE
Display response to everyone without showing original command

### ISSUE THREAD

**Issue by jryd** [spatie/laravel-slack-slash-command#43]
I have successfully implemented this package and have a mix of commands that either display to everyone or just the user that has typed it.

I notice that when the response is just being displayed to the user, that is to say when `displayResponseToEveryoneOnChannel()` is not used, the command I type in is not shown and I only see the response.

However when the response is being displayed to everyone, so when `displayResponseToEveryoneOnChannel()` is used, the command I typed in is shown along with the response.

Is there a way to show the response to everyone on the channel without displaying the command that generated it?

As per my example below, everyone on the channel can see I typed `/jeeves up` to get the response `The server is up.`

![image](https://cloud.githubusercontent.com/assets/13251203/21835749/393dc890-d80b-11e6-92c8-5cd0ac39ad77.png)

**Comment by freekmurze** [comment]
In my setup the initial command I'm giving isn't even displayed in the chat channel why I press enter? 

Maybe this is some setting on the Slack channel itself?

**Comment by royduin** [comment]
Did you figure this out @jryd? Having the same problem
