### ISSUE TITLE
Multiple commands have multiple tokens as well

### ISSUE THREAD

**Issue by drakakisgeo** [spatie/laravel-slack-slash-command#44]
I must be missing something really obvious, so I would love some help with this one.

Each slack command seems to have a completely different "SLACK_SLASH_COMMAND_VERIFICATION_TOKEN" that can't be forced to be the same one in the slack settings.

In the package you only give the option for one, so I get a "wrong token" error when I use more than one commands.

I managed to bypass this by using signatures but its not ideal for my case.

**Comment by freekmurze** [comment]
I'm probably going to abandon this package soon. Take a look at the more feature complete [botman package](https://github.com/mpociot/botman).
