### ISSUE TITLE
Could not find package spatie/laravel-slack-slash-command at any version matching your PHP version 5.6.4.0

### ISSUE THREAD

**Issue by JustSteveKing** [spatie/laravel-slack-slash-command#53]
Not sure what is happening here, it has happened on a few Spatie packages ...

![screen shot 2017-08-09 at 21 18 51](https://user-images.githubusercontent.com/6368379/29142051-8abc93f8-7d48-11e7-9e6e-abe31cf2ca20.png)

**Comment by freekmurze** [comment]
I cannot recreate this problem. Seems like there's something wrong at your end. Could you try it on another compoter?

**Comment by chrisparana** [comment]
Your laravel project was probably set up initially on a machine that had that version of php installed. Check your composer.json file and look for the config at the end:
`"config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "7.1"
        }
    }`

Change the php to the correct version. Also, when you're in development and your host machine has different versions than the production or vm machine it's useful to use the `--ignore-platform-reqs` flag with composer.

**Comment by JustSteveKing** [comment]
Perfect! I was using `laravel new ...` and it seemed to add that there! Thanks for pointing it out!
