### ISSUE TITLE
FatalThrowableError: Class 'App\SlashCommandHandlers\Attachment' not found

### ISSUE THREAD

**Issue by chrisparana** [spatie/laravel-slack-slash-command#55]
While following the tutorial, a class not found error is thrown when using the examples that use attachments unless the following is added:

`use Spatie\SlashCommand\Attachment;`
`use Spatie\SlashCommand\AttachmentField;`

Not sure if this the correct behavior or if something is wrong with my set up. If these should be included, it should note this in the tutorial documentation.

**Comment by freekmurze** [comment]
Could you send a PR to fix this?

**Comment by chrisparana** [comment]
I'm not sure this is something for a pull request… The issue is either I'm misunderstanding something, or the documentation is not specific enough. I have nothing to change the source. Is the behavior when creating a new handler that you need to include those lines when using attachments? For example:

```
<?php
namespace App\SlashCommandHandlers;


use Spatie\SlashCommand\Request;
use Spatie\SlashCommand\Response;
use Spatie\SlashCommand\Handlers\BaseHandler;
use Spatie\SlashCommand\Attachment;
use Spatie\SlashCommand\AttachmentField;
```

Also, another case where I'm getting this type of error, again following the tutorial is the SlowApi example. "FatalThrowableError: Class 'App\SlashCommandHandlers\SlowApiJobJob' not found in /home/vagrant/Code/app/SlashCommandHandlers/SlowApi.php:34"

This however I'm not able to resolve by adding:

`use App\SlashCommandHandlers\SlowApiJobJob;`

So is there something I'm missing here?

**Comment by chrisparana** [comment]
Under further experimentation I figured this out. Sorry, I'm relatively new to Laravel and just misunderstood somethings, and didn't realize in the tutorial that they weren't complete working examples. Everything is working great now.
