### ISSUE TITLE
[Question] Would you think of maybe implementing 

### ISSUE THREAD

**Issue by Caroga** [spatie/laravel-slack-slash-command#67]
Would you think of maybe implementing the ability to start sending dialog responses to slack? In conjunction with the existing delayed response setup this would be a great addition to the existing library.

**Comment by freekmurze** [comment]
We don't to any active development on this package anymore. Please take a look at an alternative like the excellent BotMan.

**Comment by Caroga** [comment]
Thanks for the reference. Are you guys looking for maintainers to take ownership of this project?

**Comment by freekmurze** [comment]
We could use active contributors. We still like to maintain control. Active contributors could get write permissions.

**Comment by Caroga** [comment]
Good. I'll might join in due time, currently need to finish this project first. I'll get back to you by then.
:+1:
