### ISSUE TITLE
Argument 2 must be an instance of Spatie\SlashCommand\string, string given

### ISSUE THREAD

**Issue by johanholm** [spatie/laravel-slack-slash-command#7]
Im not sure if this is a bug or if I've set up my system wrong.
Im running Laravel 5.2 (stable) with homestead and hhvm enabled.

When i try to run the standard hodor command I get the message
`Argument 2 passed to Spatie\SlashCommand\Request::__invoke() must be an instance of Spatie\SlashCommand\string, string given`

Its like the typehint string for $propertyName in /src/Request.php:49 thinks it need a  Spatie\SlashCommand\String instead of a actual string

Could you tell me what im doing wrong?

**Comment by freekmurze** [comment]
I guess this has to do with the fact you're on hhvm. Could you try in a homestead box with php?
