### ISSUE TITLE
Update to work with Laravel 6

### ISSUE THREAD

**Issue by chrisjohnleah** [spatie/laravel-slack-slash-command#84]
Can you please, update this to work with Laravel 6?

Composer issue:
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.0.1
    - Conclusion: don't install laravel/framework v6.0.1`

**Comment by freekmurze** [comment]
I just tagged a L6 compatible release.
