### ISSUE TITLE
[New feature] Dialog forms

### ISSUE THREAD

**Issue by chrisjohnleah** [spatie/laravel-slack-slash-command#86]
As Slash commands are great for invocating other interactive features, is it possible you could extend this to allow a respondToSlackWithDialog() method? That allows us to return and invoke a dialog.open method in Slack?

I was working on this on my own fork but extending it was taking me away from my main MVP idea for my app so I stopped, but if you could consider this as a feature, that would be great.

**Comment by freekmurze** [comment]
Currently I'm not using this package myself anymore, so I'm not going to invest time in adding features. I do accept simple PRs with tests and an updated readme though.
