### ISSUE TITLE
Error 500 when a second handler is added

### ISSUE THREAD

**Issue by selimirez** [spatie/laravel-slack-slash-command#87]
I've been following the instructions and I believe I set it all up correctly and my Hodor class works as it should, but when I add a second handler like the Repeat class from examples and register it, the whole program breaks and returns error 500 for both classes.

I would really appreciate it if you could point me in the right direction please as I can't figure out what I am doing wrong, thanks a lot

**Comment by mul14** [comment]
Please check the error message. By default it stored at `storage/logs` folder.

**Comment by selimirez** [comment]
The logs show that "There is no class named `Spatie\SlashCommand\Handlers\Repeat`"

This happens even when I change the name of my existing Hodor class to Repeat or another name. So the Hodor class only works when it is called "Hodor", and breaks when I change the class name on the handler file and in the list of handlers.
