### ISSUE TITLE
Command failed with the error "http_client_error"

### ISSUE THREAD

**Issue by promatik** [spatie/laravel-slack-slash-command#99]
I'm having the error "http_client_error" on slack when trying to call any command.

When I created a request on Postman, if I set the `Content-Type` to `multipart/form-data` everything works great, but when I change it to `application/x-www-form-urlencoded`, it doesn't work.

I tried the `application/x-www-form-urlencoded` because it's [stated in the documentation](https://api.slack.com/interactivity/slash-commands#app_command_handling):
> _This data will be sent with a` Content-type` header set as `application/x-www-form-urlencoded`._

Maybe slack changed the way it creates the http request for new apps? Just a guess ...

**Comment by makerstorage** [comment]
same is here

**Comment by promatik** [comment]
Today I tried once again, and I found out the problem was an ending slash on the Request URL.

![image](https://user-images.githubusercontent.com/1838187/94616320-dd8d9b00-02a0-11eb-9af0-09ee09483ade.png)

I'm ashamed 🤦‍♂️
For future reference, that slash cannot be there.
